name: python-asyncio-lessons | Pull requests validation

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:

jobs:
  validation:
    name: Codestyle and tests validation
    runs-on: ubuntu-latest
    steps:
      - name: Clone our repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Lint with pycodestyle
        run: |
          source venv/bin/activate
          pycodestyle --exclude=venv --max-line-length=80 .